### ISSUE TITLE
Switch to TreeKIT-hosted tiles 

### ISSUE THREAD

**Issue by fkh** [treekit/treekit#49]
Heads up, you are still using tiles from OpenPlans' mapbox account. Please switch to tiles in a Mapbox account owned by TreeKIT, or use one of the public tile URLs.

Here's where the tiles are currently set -- 
https://github.com/treekit/treekit/blob/5c402e08751c31e0a69d86edb13ad2790bcc5e48/app/scripts/config.js#L13-L20

**Comment by ebarry** [comment]
Hi Frank. Thank you so much for this heads up. Super helpful.
So, these were custom tiles that (i think) Vizzuality made. Do you know how
can i move the tiles themselves to a new account or should i ask Mapbox
(probably i'd ask Alex)?

--

@lizbarry <http://twitter.com/lizbarry>
